import { useState } from "react";
import toast from "react-hot-toast";
import {
  PiExportBold,
  PiFileCsvBold,
  PiFileTextBold,
  PiFilePdfBold,
  PiHeartbeatBold,
  PiBrainBold,
  PiShieldBold,
  PiListChecksBold,
  PiArrowsClockwiseBold,
  PiCheckCircleBold,
  PiXCircleBold,
} from "react-icons/pi";

import Card from "../components/Card.jsx";
import { exportReport } from "../services/api.js";

const FORMATS = [
  { key: "csv", label: "CSV", icon: PiFileCsvBold, available: true },
  { key: "json", label: "JSON", icon: PiFileTextBold, available: true },
  { key: "pdf", label: "PDF", icon: PiFilePdfBold, available: false },
];

const CATEGORIES = [
  { key: "monitoring", label: "Monitoring Reports", icon: PiHeartbeatBold },
  { key: "ai", label: "AI Reports", icon: PiBrainBold },
  { key: "cybersecurity", label: "Cybersecurity Reports", icon: PiShieldBold },
  { key: "test_runs", label: "Complete Test Runs", icon: PiListChecksBold },
];

function jobKey(category, format) {
  return `${category}:${format}`;
}

function triggerDownload(blob, filename) {
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  window.URL.revokeObjectURL(url);
}

/**
 * Export — the report export workspace. Lets the user choose an export
 * format (CSV, JSON, PDF placeholder) for a report category
 * (monitoring, AI, cybersecurity, complete test runs) and delegates
 * the actual file generation to the backend via
 * services/api.js::exportReport(category, format). This component
 * never generates or assembles export files itself — it only
 * triggers the request, tracks per-job progress, surfaces
 * success/error toasts, and downloads the blob the backend returns.
 *
 * Props:
 *   reports (array) — optional report list from Reports.jsx, accepted
 *                      for prop compatibility (e.g. to show a count),
 *                      not used for export generation.
 */
function Export({ reports = [] }) {
  const [jobs, setJobs] = useState({});

  const setJobStatus = (category, format, statusUpdate) => {
    setJobs((prev) => ({
      ...prev,
      [jobKey(category, format)]: { ...prev[jobKey(category, format)], ...statusUpdate },
    }));
  };

  const handleExport = async (category, format) => {
    const formatMeta = FORMATS.find((f) => f.key === format);
    if (!formatMeta?.available) {
      toast("PDF export is coming soon.", { icon: "🚧" });
      return;
    }

    const key = jobKey(category, format);
    setJobStatus(category, format, { status: "loading", error: null });

    try {
      const response = await exportReport(category, format);

      const blob =
        response instanceof Blob
          ? response
          : new Blob(
              [typeof response === "string" ? response : JSON.stringify(response, null, 2)],
              { type: format === "csv" ? "text/csv" : "application/json" }
            );

      const filename = `lavender-trinetra_${category}_${new Date()
        .toISOString()
        .slice(0, 19)
        .replace(/[:T]/g, "-")}.${format}`;

      triggerDownload(blob, filename);

      setJobStatus(category, format, { status: "success" });
      toast.success(`${CATEGORIES.find((c) => c.key === category)?.label} exported as ${formatMeta.label}.`);
    } catch (err) {
      setJobStatus(category, format, { status: "error", error: err?.message || "Export failed." });
      toast.error(`Failed to export ${category.replace(/_/g, " ")} as ${formatMeta.label}.`);
    } finally {
      setTimeout(() => {
        setJobs((prev) => {
          const current = prev[key];
          if (!current || current.status === "loading") return prev;
          const next = { ...prev };
          delete next[key];
          return next;
        });
      }, 4000);
    }
  };

  return (
    <Card title="Export Reports" icon={PiExportBold}>
      <div className="flex flex-col gap-5">
        <p className="text-sm text-[var(--color-text-secondary,#94a3b8)]">
          Export stored monitoring, AI, and cybersecurity data. Files are generated by the
          backend and downloaded directly.
        </p>

        {CATEGORIES.map(({ key: categoryKey, label, icon: CategoryIcon }) => (
          <div
            key={categoryKey}
            className="rounded-lg border border-[var(--color-border,#232733)] p-3"
          >
            <div className="mb-3 flex items-center gap-2">
              <CategoryIcon className="h-4 w-4 text-violet-400" />
              <span className="text-sm font-medium text-[var(--color-text-primary,#f1f5f9)]">
                {label}
              </span>
            </div>

            <div className="flex flex-wrap gap-2">
              {FORMATS.map(({ key: formatKey, label: formatLabel, icon: FormatIcon, available }) => {
                const job = jobs[jobKey(categoryKey, formatKey)];
                const isLoading = job?.status === "loading";
                const isSuccess = job?.status === "success";
                const isError = job?.status === "error";

                return (
                  <button
                    key={formatKey}
                    type="button"
                    disabled={isLoading || !available}
                    onClick={() => handleExport(categoryKey, formatKey)}
                    title={!available ? `${formatLabel} export coming soon` : `Export as ${formatLabel}`}
                    className={`flex items-center gap-1.5 rounded-md border px-3 py-1.5 text-xs font-medium transition-colors ${
                      !available
                        ? "cursor-not-allowed border-[var(--color-border,#232733)] text-[var(--color-text-secondary,#64748b)] opacity-50"
                        : isError
                        ? "border-rose-500/40 text-rose-300 hover:bg-rose-500/10"
                        : isSuccess
                        ? "border-emerald-500/40 text-emerald-300"
                        : "border-[var(--color-border,#232733)] text-[var(--color-text-secondary,#94a3b8)] hover:bg-white/5 hover:text-[var(--color-text-primary,#f1f5f9)]"
                    }`}
                  >
                    {isLoading ? (
                      <PiArrowsClockwiseBold className="h-3.5 w-3.5 animate-spin" />
                    ) : isSuccess ? (
                      <PiCheckCircleBold className="h-3.5 w-3.5" />
                    ) : isError ? (
                      <PiXCircleBold className="h-3.5 w-3.5" />
                    ) : (
                      <FormatIcon className="h-3.5 w-3.5" />
                    )}
                    {formatLabel}
                    {!available && (
                      <span className="rounded-full bg-white/10 px-1.5 py-0.5 text-[10px] uppercase tracking-wide">
                        Soon
                      </span>
                    )}
                  </button>
                );
              })}
            </div>

            {jobs[jobKey(categoryKey, "csv")]?.status === "error" && (
              <p className="mt-2 text-xs text-rose-400">
                {jobs[jobKey(categoryKey, "csv")].error}
              </p>
            )}
            {jobs[jobKey(categoryKey, "json")]?.status === "error" && (
              <p className="mt-2 text-xs text-rose-400">
                {jobs[jobKey(categoryKey, "json")].error}
              </p>
            )}
          </div>
        ))}
      </div>
    </Card>
  );
}

export default Export;